### PR TITLE
add keyNoCollision method to MyHashtable.java

### PR DESCRIPTION
**Pull request by petprog**
I added `keyNoCollision()` method in MyHashTable
### Hash collision prevention
A bonus file was added in the course. So, I feel this needs to be updated [course-link](https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/learn/lecture/18266492#overview)

Kindly check it out

### CODE REVIEW

**Comment by nimrod46** [comment]
Amm... what benefit does it have over the current keys method that is implemented in the class?

**Comment by petprog** [comment]
> 
> 
> Amm... what benefit does it have over the current keys method that is implemented in the class?

Thanks for asking this questions. I noticed there is no difference when I implemented the no key collision method in Java from the JS code provided. I just see that the class needs to be implemented because It was provided in the course too.

Thanks.

**Comment by nimrod46** [comment]
> > Amm... what benefit does it have over the current keys method that is implemented in the class?
> 
> Thanks for asking this questions. I noticed there is no difference when I implemented the no key collision method in Java from the JS code provided. I just see that the class needs to be implemented because It was provided in the course too.
> 
> Thanks.

Well, I already provided in my `keys()` method the same solution with java code, I just didn't mention that it will also work with collision keys because I think it's mandatory to do so in this case. So I see no reason to impl the method given in JS, it's different from the `keys' method only because it was implemented in a different language.

If you have any other comments on the project feel free to add! it's nice seeing ppl using this project :D

**Comment by petprog** [comment]
You welcome.

**Pull request closed without merging**
